#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/ci/frontend-build"

cd "${DIR}/../.."

# Buildx Builder
docker buildx create --name "Buildx-NPM" || echo
docker buildx use "Buildx-NPM"

docker buildx build -f docker/Dockerfile $BUILD_TAG --platform $BUILD_PLATFORM . --push

docker buildx rm "Buildx-NPM"

echo "已完成多架构构建！"